name:                haboli
version:             0.1.0.0
github:              "Garmelon/haboli"
license:             BSD3
author:              "Garmelon"
maintainer:          "joscha@plugh.de"
copyright:           "2020 Garmelon"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Garmelon/haboli#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- bytestring
- containers
- network
- stm
- text
- time
- transformers
- unordered-containers
- websockets
- wuss

library:
  source-dirs: src

executables:
  haboli-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haboli

tests:
  haboli-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haboli
