name: haboli
version: 0.3.1.0
license: MIT
author: Garmelon <joscha@plugh.de>
copyright: 2020 Garmelon

synopsis: API bindings for https://euphoria.io/
description: Please see the README on GitHub at <https://github.com/Garmelon/haboli#readme>
github: Garmelon/haboli

extra-source-files:
  - README.md
  - CHANGELOG.md
  - LICENSE

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - containers
  - network
  - stm
  - text
  - time
  - transformers
  - unordered-containers
  - websockets
  - wuss

library:
  source-dirs: src
